### ISSUE TITLE
Include gnome-software-rpm-ostree?

### ISSUE THREAD

**Issue by bronson** [ublue-os/budgie#38]
### Describe the package

Is there a reason Gnome Software is not included in this image?

I layered it (`rpm-ostree install gnome-software-rpm-ostree`) and it works great.

I'm running `ostree-image-signed:docker://ghcr.io/ublue-os/budgie-main:38`, rebased from Silverblue.

### Image

All Images

**Comment by castrojo** [comment]
Added, thanks!
